version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: BNIA_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword    # mot de passe root (change si besoin)
      MARIADB_DATABASE: BNIA           # base de données à créer
      MARIADB_USER: BNIAuser                 # utilisateur BDD
      MARIADB_PASSWORD: BNIApass             # mot de passe utilisateur
    ports:
      - "3317:3306"                           # port hôte : port conteneur
    volumes:
      - mariadb_BNIA_data:/var/lib/mysql  # volume persistant

volumes:
  mariadb_BNIA_data: